spring:
  datasource:
    # url: ${DEV_DB}
    # username: ${DEV_USERNAME}
    # password: ${DEV_PASSWORD}
    # hikari:
    #   maximum-pool-size:
    #   minimum-idle: ${읽기 작업이 언제든 가능한 수준으로}
    #   connection-timeout:
    #   idle-timeout:
  sql:
    init:
      mode: never # 개발 환경 스키마를 따름

logging:
  level:
    root: info