spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:celebe-local.db
  sql:
    init:
      schema-locations: classpath:schema.sql

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: io.celebe.challenge.**.domain, io.celebe.challenge.**.dto

logging:
  level:
    root: info
    io.celebe.challenge: debug
    org.mybatis: debug
    org.springframework:
      jdbc: debug
      test: debug
      transaction: debug
